export default [
  {
    login: "Ofunmi",
    id: 63416790,
    node_id: "MDQ6VXNlcjYzNDE2Nzkw",
    avatar_url: "https://avatars.githubusercontent.com/u/63416790?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Ofunmi",
    html_url: "https://github.com/Ofunmi",
    followers_url: "https://api.github.com/users/Ofunmi/followers",
    following_url: "https://api.github.com/users/Ofunmi/following{/other_user}",
    gists_url: "https://api.github.com/users/Ofunmi/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Ofunmi/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Ofunmi/subscriptions",
    organizations_url: "https://api.github.com/users/Ofunmi/orgs",
    repos_url: "https://api.github.com/users/Ofunmi/repos",
    events_url: "https://api.github.com/users/Ofunmi/events{/privacy}",
    received_events_url: "https://api.github.com/users/Ofunmi/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "onlydozie",
    id: 64152426,
    node_id: "MDQ6VXNlcjY0MTUyNDI2",
    avatar_url: "https://avatars.githubusercontent.com/u/64152426?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/onlydozie",
    html_url: "https://github.com/onlydozie",
    followers_url: "https://api.github.com/users/onlydozie/followers",
    following_url:
      "https://api.github.com/users/onlydozie/following{/other_user}",
    gists_url: "https://api.github.com/users/onlydozie/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/onlydozie/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/onlydozie/subscriptions",
    organizations_url: "https://api.github.com/users/onlydozie/orgs",
    repos_url: "https://api.github.com/users/onlydozie/repos",
    events_url: "https://api.github.com/users/onlydozie/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/onlydozie/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "eddy1759",
    id: 59479466,
    node_id: "MDQ6VXNlcjU5NDc5NDY2",
    avatar_url: "https://avatars.githubusercontent.com/u/59479466?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/eddy1759",
    html_url: "https://github.com/eddy1759",
    followers_url: "https://api.github.com/users/eddy1759/followers",
    following_url:
      "https://api.github.com/users/eddy1759/following{/other_user}",
    gists_url: "https://api.github.com/users/eddy1759/gists{/gist_id}",
    starred_url: "https://api.github.com/users/eddy1759/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/eddy1759/subscriptions",
    organizations_url: "https://api.github.com/users/eddy1759/orgs",
    repos_url: "https://api.github.com/users/eddy1759/repos",
    events_url: "https://api.github.com/users/eddy1759/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/eddy1759/received_events",
    type: "User",
    site_admin: false,
  },
];
