export default {
  login: "Hassan-Ib",
  id: 53692907,
  node_id: "MDQ6VXNlcjUzNjkyOTA3",
  avatar_url: "https://avatars.githubusercontent.com/u/53692907?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Hassan-Ib",
  html_url: "https://github.com/Hassan-Ib",
  followers_url: "https://api.github.com/users/Hassan-Ib/followers",
  following_url:
    "https://api.github.com/users/Hassan-Ib/following{/other_user}",
  gists_url: "https://api.github.com/users/Hassan-Ib/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Hassan-Ib/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Hassan-Ib/subscriptions",
  organizations_url: "https://api.github.com/users/Hassan-Ib/orgs",
  repos_url: "https://api.github.com/users/Hassan-Ib/repos",
  events_url: "https://api.github.com/users/Hassan-Ib/events{/privacy}",
  received_events_url: "https://api.github.com/users/Hassan-Ib/received_events",
  type: "User",
  site_admin: false,
  name: "Ibrahim Hassan-SilverTongue",
  company: null,
  blog: "",
  location: "Oshogbo, Osun state, Nigeria",
  email: null,
  hireable: null,
  bio: null,
  twitter_username: "Azanebrahim",
  public_repos: 34,
  public_gists: 0,
  followers: 3,
  following: 7,
  created_at: "2019-08-04T10:05:27Z",
  updated_at: "2021-02-01T04:40:59Z",
};
